services:
  mysql-dev:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: haritha
      MYSQL_DATABASE: gramaCheckTest
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ../generated/db/script.sql:/docker-entrypoint-initdb.d/1.sql
